name: lint-sql.yml

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'init/') || startsWith(github.head_ref, 'feat/')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linters
        run: |
          python -m pip install -U pip
          pip install sqlfluff yamllint

      - name: SQLFluff
        run: >
          sqlfluff lint sql
          --dialect tsql
          --exclude-rules CP02,RF04,LT05

      - name: Yamllint
        run: |
          yamllint -f parsable \
            -d "{extends: default, rules: {line-length: disable, truthy: disable, document-start: disable}}" \
            sql
      
